//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int id { get; set; }
        public string Banner_name { get; set; }
        public string Banner_image { get; set; }
        public string slug { get; set; }
    }
}
