//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string Book_id { get; set; }
        public string titleBook { get; set; }
        public string content { get; set; }
        public string bookImage { get; set; }
        public string slug { get; set; }
        public string Flavor_id { get; set; }
        public string author { get; set; }
        public Nullable<int> priceBook { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> quantity_sold { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    
        public virtual Flavor Flavor { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
