//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Flavor
    {
        public Flavor()
        {
            this.Books = new HashSet<Book>();
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int id { get; set; }
        [Display(Name = "Flavor ID")]
        [Required(ErrorMessage = "Not Null")]
        public string Flavor_id { get; set; }

        [Display(Name = "Flavor Title")]
        [Required(ErrorMessage = "Not Null")]
        public string Flavor_title { get; set; }
        [Display(Name = "Flavor Image")]
        [Required(ErrorMessage = "Not Null")]
        public string Flavor_image { get; set; }
        public string slug { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
