//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string transactions_id { get; set; }
        public string Book_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> total_price { get; set; }
        public string data { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
