//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentForRegisterdUser
    {
        public int PaymentId { get; set; }
        public Nullable<int> RegisteredUser_id { get; set; }
        public int payfor { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
