//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int id { get; set; }
        public string Recipe_id { get; set; }
        public string Recipe_title { get; set; }
        public string Recipe_image { get; set; }
        public string slug { get; set; }
        public string Recipe_ingredients { get; set; }
        public string Recipe_procedure { get; set; }
        public string Flavor_id { get; set; }
        public string Recipe_Author { get; set; }
    
        public virtual Flavor Flavor { get; set; }
    }
}
