//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public RegisteredUser()
        {
            this.PaymentForRegisterdUsers = new HashSet<PaymentForRegisterdUser>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int RegisteredUser_id { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string avatar { get; set; }
        public int payfor { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    
        public virtual ICollection<PaymentForRegisterdUser> PaymentForRegisterdUsers { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
