//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public string Book_id { get; set; }
        public int RegisteredUser_id { get; set; }
        public int Visitor_id { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string description { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual RegisteredUser RegisteredUser { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
