//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP3_ICE_CREAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public string transactions_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> RegisteredUser_id { get; set; }
        public Nullable<int> Visitor_id { get; set; }
        public string username { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<int> total_price { get; set; }
        public string payment { get; set; }
        public string payment_info { get; set; }
        public string message { get; set; }
        public string security { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> shipping { get; set; }
    }
}
